version: '3.0'
name: wui
services:
  web:
    container_name: wui_container
    image: mochrira/dev:latest
    volumes:
      - ./:/workspace
    networks:
      - environment
    environment:
      - NG_INSTALL=YES
      - NG_VERSION=17

networks:
  environment:
    name: environment
    external: true